[[data]]
"विषयः" = 'व्याकरणम्, निरुक्तिः, भाषा-विज्ञानम्'
"नाम" = 'शब्दशास्त्रम्'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/shabda-shAstram'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"नाम" = 'ಕನ್ನಡ-ವ್ಯಾಸಂಗ'
"विषयः" = ''
"नियमाः" = 'ಕನ್ನಡಪ್ರಯೋಗವೇ ವರ.'
"स्तरः (1-5)" = 'माध्यमिकः'
"क्रियाशीलता (1-5)" = 1
"Platform" = 'Whatsapp'
"सङ्केतः" = ''
"उदाहरणसन्देशाः" = ''
"विवरणानि" = 'https://archive.org/search.php?query=uploader%3A%22vishvas.vasuki%40gmail.com%22%20kumAra'


[[data]]
"नाम" = 'English literature'
"विषयः" = ''
"नियमाः" = ''
"स्तरः (1-5)" = 'माध्यमिकः'
"क्रियाशीलता (1-5)" = 1
"Platform" = 'Whatsapp'
"सङ्केतः" = ''
"उदाहरणसन्देशाः" = ''
"विवरणानि" = ''


[[data]]
"नाम" = 'Tamil guides तमिळ्'
"विषयः" = 'तमिळ्'
"नियमाः" = ''
"स्तरः (1-5)" = 'माध्यमिकः'
"क्रियाशीलता (1-5)" = 1
"Platform" = 'Telegram'
"सङ्केतः" = ''
"उदाहरणसन्देशाः" = ''
"विवरणानि" = ''

