[[data]]
"विषयः" = 'संस्कृत-साङ्गणकाः / sanskrit code'
"नाम" = 'sanskrit code'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/sanskrit-programmers'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'OCR and Proofreading'
"नाम" = 'Indic OCR'
"सङ्केतः" = 'https://groups.google.com/g/indic-ocr'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'OCR and Proofreading'
"नाम" = 'Digital sanskrit temp'
"सङ्केतः" = 'https://groups.google.com/g/digital-sanskrit-temps'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"नाम" = 'संस्कृत-साङ्गणकाः / sanskrit code'
"विषयः" = 'sanskrit code'
"नियमाः" = 'https://groups.google.com/forum/#!forum/sanskrit-programmers'
"स्तरः (1-5)" = 'सार्वत्रिकः'
"क्रियाशीलता (1-5)" = 2
"Platform" = 'Whatsapp'
"सङ्केतः" = 'http://bit.ly/sanskrit-code-whatsapp'
"उदाहरणसन्देशाः" = ''
"विवरणानि" = ''

[[data]]
"नाम" = 'संस्कृत-साङ्गणकाः / sanskrit code'
"विषयः" = 'sanskrit code'
"नियमाः" = 'https://groups.google.com/forum/#!forum/sanskrit-programmers'
"स्तरः (1-5)" = 'सार्वत्रिकः'
"क्रियाशीलता (1-5)" = 2
"Platform" = 'Telegram'
"सङ्केतः" = 'https://t.me/sanskrit_coders'
"उदाहरणसन्देशाः" = ''
"विवरणानि" = ''


[[data]]
"विषयः" = 'OCR and Proofreading'
"नाम" = 'Indic OCR'
"स्तरः (1-5)" = 'सार्वत्रिकः'
"क्रियाशीलता (1-5)" = 2
"Platform" = 'Telegram'
"सङ्केतः" = 'https://t.me/indic_ocr'
"उदाहरणसन्देशाः" = ''
"विवरणानि" = ''

