baseURL = "https://sanskrit.github.io/"
languageCode = "en-us"
title = "संस्कृतजालक्षेत्रम्"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true

[outputs]
  home = ["HTML", "RSS", "JSON", "CSV"]
  section = ["HTML", "RSS", "JSON"]

[params]
  githubEditMePathBase = "https://github.com/sanskrit/sanskrit.github.io/edit/master/content/"
  contactLink = "https://github.com/sanskrit/sanskrit.github.io/issues/new"
  env = "production"
  # disqusShortcode = "sanskrit-projects-site"

[markup.goldmark.renderer]
   unsafe = true


[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[markup.goldmark.parser.attribute]
block = true
title = true

[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  hl_Lines = ''
  lineAnchors = ''
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = true
  style = 'friendly'
  tabWidth = 2
