[[data]]
"विषयः" = 'भारतीय-विद्याः'
"नाम" = 'हिन्दु-विद्या'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/hindu-vidya'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = '4'
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'भारतीय-विद्याः'
"नाम" = 'हिन्दु-विद्या'
"सङ्केतः" = 'https://groups.google.com/g/meta-indology'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = 'Focus: Analyze the political, social and cultural ramifications of Indology. This is not an indology list, rather it is a meta-indology list.​ The subject of Indology is India, the subject of meta-Indology is the discipline of Indology. Appreciation and criticism of Indology are both welcome.'
"सक्रियता" = '4'
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'भारतीय-विद्याः'
"नाम" = 'हिन्दु-विद्या'
"सङ्केतः" = 'https://discord.gg/KGk558erJV'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = 'Cover mail-streams/ channels we frequently use, including mailstreams such as hindu-vidya, meta-indology, kannada, tamil, shabda-shAstram etc..'
"सक्रियता" = '3'
"Platform" = 'Discord'

[[data]]
"विषयः" = 'कल्पः, प्रयोगः'
"नाम" = 'कल्पः, प्रयोगः'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/kalpa-prayoga'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = '2'
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'चेतो-देव-जीवादि-तत्त्व-विचारः'
"नाम" = 'चेतो-देव-जीवादि-तत्त्व-विचारः'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/cheto-deva-jivadi'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = '2'
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'तन्त्रम् आगमाश्च'
"नाम" = 'तन्त्रोल्लासः'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/tantrollAsaH'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = '2'
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'कल्पः, प्रयोगः'
"नाम" = 'कल्पः, प्रयोगः'
"सङ्केतः" = 'https://t.me/kalpaH'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = '2'
"Platform" = 'Telegram'

[[data]]
"विषयः" = ''
"नाम" = 'द्युगङ्गा dyugangA'
"सङ्केतः" = 'https://t.me/dyugangA_supporters'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = '2'
"Platform" = 'Telegram'

[[data]]
"विषयः" = ''
"नाम" = 'द्युगङ्गा dyugangA'
"सङ्केतः" = 'https://groups.google.com/g/dyuganga'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = '2'
"Platform" = 'Google groups'

[[data]]
"विषयः" = ''
"नाम" = 'श्रीवैष्णवसभा shrIvaiShNavasabhA'
"सङ्केतः" = 'https://t.me/+ReBD43LyyoWFpXFF'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = '2'
"Platform" = 'Telegram'

[[data]]
"नाम" = 'श्रीवैष्णवसभा'
"विषयः" = 'श्रीवैष्णवसंप्रदायः'
"नियमाः" = 'नास्ति भाषानियमः। संस्कृतं प्रायेण।'
"स्तरः (1-5)" = 'सार्वत्रिकः'
"क्रियाशीलता (1-5)" = 2
"Platform" = 'Whatsapp'
"सङ्केतः" = 'https://chat.whatsapp.com/2rn1j1RQxzK57Rh2V11JAL'
"उदाहरणसन्देशाः" = ''
"विवरणानि" = ''

[[data]]
"नाम" = 'सुभाषित-गोष्ठी'
"विषयः" = 'सुभाषितानि'
"नियमाः" = 'संस्कृतस्यैव प्रयोगः। (अनुप्रेषणेष्वपि)'
"स्तरः (1-5)" = 'सार्वत्रिकः'
"क्रियाशीलता (1-5)" = 2
"Platform" = 'Whatsapp'
"सङ्केतः" = 'https://chat.whatsapp.com/5ZPSKhaBHmkF500yfyK4UJ'
"उदाहरणसन्देशाः" = ''
"विवरणानि" = 'https://archive.org/search.php?query=uploader%3A%22vishvas.vasuki%40gmail.com%22%20subhAShita'

[[data]]
"नाम" = 'धर्म-जिज्ञासवः dharma-jijJNAsavaH'
"विषयः" = 'धर्मः, हिन्दुर्वम्'
"नियमाः" = '''
विषयः -  धर्मः, हिन्दुर्वम्
भाषा - संस्कृतम् आङ्ग्लिकी वा।'''
"स्तरः (1-5)" = ''
"क्रियाशीलता (1-5)" = 1
"Platform" = 'Telegram'
"सङ्केतः" = 'https://t.me/joinchat/IJu_TkduB-Q-P9nsxb0G0w'
"उदाहरणसन्देशाः" = ''
"विवरणानि" = ''
