[[data]]
"नाम" = 'शाब्दिक-परिषत्'
"विषयः" = 'व्याकरणम्'
"नियमाः" = 'संस्कृतस्यैव प्रयोगः। (अनुप्रेषणेष्वपि)। व्याकरविषयश्चैव स्यात्।'
"स्तरः (1-5)" = 'प्रगतः'
"क्रियाशीलता (1-5)" = 2
"Platform" = 'Whatsapp'
"सङ्केतः" = ''
"उदाहरणसन्देशाः" = ''
"विवरणानि" = ''

[[data]]
"विषयः" = 'भारतीय-विद्याः'
"नाम" = 'भारतीयविद्वत्-परिषत्'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/bvparishat'
"भाषा" = 'संस्कृतम्, आङ्ग्लिकम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"विषयः" = 'भारतीय-विद्याः'
"नाम" = 'शास्त्रम्'
"सङ्केतः" = 'https://groups.google.com/forum/#!forum/shaastram'
"भाषा" = 'संस्कृतम्'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Google groups'

[[data]]
"नाम" = 'शास्त्रचन्द्रिका'
"विषयः" = 'शास्त्राणि'
"नियमाः" = '''
गणस्य मुख्योद्देश्यम् – सकलशास्त्रविचाराणामेकं स्थानं भवेदिति धिया समूहोऽयमारब्धः। 
कार्यम् – सकल शास्त्रसन्देहनिवृत्तिः, शास्त्रविचाराश्च कर्तव्याः।
विधयः–
1.        अत्र चर्चाः केवलं शास्त्रसम्बद्धा एव भवेयुः।  पण्डिताः समादधति।
2.        भाषा – चर्चायां संस्कृतभाषानिवार्या। देवनागरी-टङ्कणाय Google play store इत्यत्र लभ्यमान: app  प्रयोक्तव्यः।
निषेधाः-
3 शास्त्रासम्बद्धानि चित्राणि न प्रेषितव्यानि ।
4         विवादाः न भवन्तु।'''
"स्तरः (1-5)" = 'प्रगतः'
"क्रियाशीलता (1-5)" = 4
"Platform" = 'Whatsapp'
"सङ्केतः" = 'https://chat.whatsapp.com/4jtNNFWCV4LC3CZpRDvaN8'
"उदाहरणसन्देशाः" = ''
"विवरणानि" = ''


[[data]]
"नाम" = 'न्यायदर्शनम्'
"विषयः" = 'न्याय-वैशेषिक-पूर्वमीमांसाः'
"नियमाः" = '''
(१) गणोsयं (तर्क)न्याय-पूर्वमीमांसा इत्यनयो: शास्त्रयो: विचारार्थं प्रारब्धः। 
(३) अत्र संस्कृतेनैव विचाराः स्युः ।'''
"स्तरः (1-5)" = 'प्रगतः'
"क्रियाशीलता (1-5)" = 3
"Platform" = 'Whatsapp'
"सङ्केतः" = 'message +91 98413 43265'
"उदाहरणसन्देशाः" = ''
"विवरणानि" = ''

[[data]]
"नाम" = 'लघुसिद्धान्तकौमुदी'
"विषयः" = 'व्याकरणम्'
"नियमाः" = 'यह समूह हिन्दी-संस्कृत समूह है । यहाँ केवल लघुसिद्धान्तकौमुदी के ही लेख /आडियो/विडियो ही प्रेषित करना है, नित्य 3 से 5 सूत्रों पर विस्तृत चर्चा हो । आगे के सूत्र अगले दिन । अत: धैर्य आवश्यक है ।'
"स्तरः (1-5)" = ''
"क्रियाशीलता (1-5)" = ''
"Platform" = 'Whatsapp'
"सङ्केतः" = 'https://chat.whatsapp.com/HykECf2l3ut67wZWHQOAA3'
"उदाहरणसन्देशाः" = ''
"विवरणानि" = ''

[[data]]
"नाम" = 'श्रीवैष्णवामृतम्'
"विषयः" = 'श्रीवैष्णवसंप्रदायः'
"नियमाः" = ''
"स्तरः (1-5)" = ''
"क्रियाशीलता (1-5)" = 1
"Platform" = 'Whatsapp'
"सङ्केतः" = 'https://chat.whatsapp.com/JOkURaEpX350uMTJ8FooLJ'
"उदाहरणसन्देशाः" = ''
"विवरणानि" = ''

[[data]]
"नाम" = 'द्वैतप्रतिष्ठानम्'
"विषयः" = 'माध्व-सम्प्रदायः'
"नियमाः" = '''
१) सर्वेपि स्व अभिप्रायं वक्तुं स्वतन्त्राः। (२) गणोऽयं  द्वैत वेदान्त विचारार्थं तथा व्याकरण , मीमांसा, तर्क , ज्योतिष ,न्याय  
शास्त्रादिकानां विचारार्थं च प्रारब्ध:। अतः अन्यविचाराः उत चित्रानि तथा videos , व्यर्थ सन्देशान् अत्र वितरणं नार्हन्ति।
… मठीयभेददर्शनं अत्र न भवेत्'''
"स्तरः (1-5)" = 'प्रगतः'
"क्रियाशीलता (1-5)" = 2
"Platform" = 'Whatsapp'
"सङ्केतः" = 'message +91 98413 43265'
"उदाहरणसन्देशाः" = ''
"विवरणानि" = ''

[[data]]
"नाम" = 'अद्वैतसभा'
"विषयः" = 'अद्वैतसभा'
"नियमाः" = '''
१) अत्र संस्कृतेनैव विचारः कर्तव्य:
२) अद्वैतवेदान्त विचारातिरिक्त अन्यविचार: अत्र नार्हन्ति |
३) व्यर्थचित्रसन्देशादिप्रेषणं अत्र न कर्तव्यम् |'''
"स्तरः (1-5)" = 'प्रगतः'
"क्रियाशीलता (1-5)" = 2
"Platform" = 'Whatsapp'
"सङ्केतः" = 'message +91 98413 43265'
"उदाहरणसन्देशाः" = ''
"विवरणानि" = ''
