[[data]]
"नाम" = 'Sathsamhita.VedAbhimAnis'
"विषयः" = 'द्रविडदेशे वेदप्रोत्साहनम्'
"नियमाः" = ''
"स्तरः (1-5)" = 'प्रगतः'
"क्रियाशीलता (1-5)" = 4
"Platform" = 'Whatsapp'
"सङ्केतः" = 'https://t.co/O7xR9Vh8C5'
"उदाहरणसन्देशाः" = ''
"विवरणानि" = ''


[[data]]
"नाम" = 'भविष्यद्भारतम्'
"विषयः" = 'अनिश्चितः'
"नियमाः" = 'संस्कृतस्यैव प्रयोगः। (अनुप्रेषणेष्वपि)'
"स्तरः (1-5)" = 'सार्वत्रिकः'
"क्रियाशीलता (1-5)" = 3
"Platform" = 'Whatsapp'
"सङ्केतः" = '<सद्यो गुप्तः>'
"उदाहरणसन्देशाः" = ''
"विवरणानि" = ''

[[data]]
"विषयः" = 'इतिहासः'
"नाम" = 'भारतीयदृष्टिः'
"सङ्केतः" = 'http://t.me/SurfingKaliYuga'
"भाषा" = 'English'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Telegram'

[[data]]
"विषयः" = 'हिन्दुत्व-पुंस्त्वम्'
"नाम" = 'रुद्राग्नी'
"सङ्केतः" = 'http://t.me/kaalaagni'
"भाषा" = 'English'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Telegram'

[[data]]
"विषयः" = 'हिन्दुत्वम्'
"नाम" = 'रुद्राग्नी'
"सङ्केतः" = 'http://t.me/CursedRaitaTakes'
"भाषा" = 'English'
"नियमाः" = ''
"सक्रियता" = ''
"Platform" = 'Telegram'

