[[data]]
"рд╡рд┐рд╖рдпрдГ" = 'рд╕рдВрд╕реНрдХреГрддрдореН'
"рдирд╛рдо" = 'рд╕рдВрд╕реНрдХреГрддрдпреВрдердореН'
"рд╕рдЩреНрдХреЗрддрдГ" = 'https://groups.google.com/forum/#!forum/samskrita'
"рднрд╛рд╖рд╛" = 'рд╕рдВрд╕реНрдХреГрддрдореН, рдЖрдЩреНрдЧреНрд▓рд┐рдХрдореН'
"рдирд┐рдпрдорд╛рдГ" = ''
"рд╕рдХреНрд░рд┐рдпрддрд╛" = ''
"Platform" = 'Google groups'

[[data]]
"рд╡рд┐рд╖рдпрдГ" = ''
"рдирд╛рдо" = 'рд╕рдВрд╕реНрдХреГрддреЗ рд╕рдВрд╡рджреЗрдо'
"рд╕рдЩреНрдХреЗрддрдГ" = 'https://groups.google.com/forum/#!forum/samskrte-samvadema'
"рднрд╛рд╖рд╛" = 'рд╕рдВрд╕реНрдХреГрддрдореН'
"рдирд┐рдпрдорд╛рдГ" = 'рд╕рдВрд╕реНрдХреГрддреЗрдиреИрд╡ рднрд╛рд╖рдгрдореН'
"рд╕рдХреНрд░рд┐рдпрддрд╛" = ''
"Platform" = 'Google groups'

[[data]]
"рд╡рд┐рд╖рдпрдГ" = 'рдкрджреНрдпрдореН'
"рдирд╛рдо" = 'рдХрд╡рдпреЛ рд╡рдпрдордореА'
"рд╕рдЩреНрдХреЗрддрдГ" = 'https://www.facebook.com/groups/padyadhaaraa/?fref=ts'
"рднрд╛рд╖рд╛" = 'рд╕рдВрд╕реНрдХреГрддрдореН'
"рдирд┐рдпрдорд╛рдГ" = ''
"рд╕рдХреНрд░рд┐рдпрддрд╛" = ''
"Platform" = 'Facebook groups'

[[data]]
"рдирд╛рдо" = 'рд╕рдВрд╕реНрдХреГрддреЗрди рдЬрд▓реНрдкрдГ'
"рд╡рд┐рд╖рдпрдГ" = 'рдЕрдирд┐рд╢реНрдЪрд┐рддрдГ'
"рдирд┐рдпрдорд╛рдГ" = '''
рд╕рдВрд╕реНрдХреГрддрд╕реНрдпреИрд╡ рдкреНрд░рдпреЛрдЧрдГред (рдЕрдиреБрдкреНрд░реЗрд╖рдгреЗрд╖реНрд╡рдкрд┐)
No other language allowed.
This group aims to facilitate samskrita conversation by enabling immersion into it. This is it's limited goal.'''
"рд╕реНрддрд░рдГ (1-5)" = 'рдордзреНрдпрдордГ'
"рдХреНрд░рд┐рдпрд╛рд╢реАрд▓рддрд╛ (1-5)" = 4
"Platform" = 'Whatsapp'
"рд╕рдЩреНрдХреЗрддрдГ" = 'https://chat.whatsapp.com/3VZF9eQ34dbKgl1vahiieQ'
"рдЙрджрд╛рд╣рд░рдгрд╕рдиреНрджреЗрд╢рд╛рдГ" = ''
"рд╡рд┐рд╡рд░рдгрд╛рдирд┐" = ''

[[data]]
"рдирд╛рдо" = 'рдкреНрд░рдгрд╡рдкрд╛рд░рд┐рдЬрд╛рддрдГ'
"рд╡рд┐рд╖рдпрдГ" = 'рдЕрдирд┐рд╢реНрдЪрд┐рддрдГ'
"рдирд┐рдпрдорд╛рдГ" = '''
рд╕рдВрд╕реНрдХреГрддреЗрди, рд╕рдВрд╕реНрдХреГрддрд╛рдп, рд╕рдВрд╕реНрдХреГрддрд╕реНрдп рдЪ рдЕрдпрдВ рд╕рдВрд╕реНрдХреГрддрд╕рдореВрд╣рдГред рднрд╛рд╖рд╛рдиреНрддрд░рдВ рд╕рд░реНрд╡рдерд╛ рдирд┐рд╖рд┐рджреНрдзрдорддреНрд░ред рд╕рдВрд╕реНрдХреГрддреЗрдиреИрд╡ рд╕реНрд╡рд╡рд┐рд╖рдпрд╕рдореБрдкрд╕реНрдерд╛рдкрдирдВ рдХреНрд░рд┐рдпрддреЗрд╜рддреНрд░ рдирд╛рдиреНрдпрднрд╛рд╖рдпрд╛ рдЗрддрд┐ рдирд┐рдпрдордГ рд╕рд░реНрд╡реИрд░рдиреБрдкрд╛рд▓рдиреАрдпрдГ рд╕рд░реНрд╡рджреИрд╡ред
'''
"рд╕реНрддрд░рдГ (1-5)" = 'рдордзреНрдпрдордГ'
"рдХреНрд░рд┐рдпрд╛рд╢реАрд▓рддрд╛ (1-5)" = 4
"Platform" = 'Whatsapp'
"рд╕рдЩреНрдХреЗрддрдГ" = 'https://chat.whatsapp.com/BiswrXEZUcP0bVzuP6bbhk'
"рдЙрджрд╛рд╣рд░рдгрд╕рдиреНрджреЗрд╢рд╛рдГ" = ''
"рд╡рд┐рд╡рд░рдгрд╛рдирд┐" = ''

[[data]]
"рдирд╛рдо" = 'рд╕рдВрд╕реНрдХреГрддреЗрди рдЬрд▓реНрдкрдГ'
"рд╡рд┐рд╖рдпрдГ" = 'рдЕрдирд┐рд╢реНрдЪрд┐рддрдГ'
"рдирд┐рдпрдорд╛рдГ" = '''
рд╕рдВрд╕реНрдХреГрддрд╕реНрдпреИрд╡ рдкреНрд░рдпреЛрдЧрдГред (рдЕрдиреБрдкреНрд░реЗрд╖рдгреЗрд╖реНрд╡рдкрд┐)
No other language allowed.
This group aims to facilitate samskrita conversation by enabling immersion into it. This is it's limited goal.'''
"рд╕реНрддрд░рдГ (1-5)" = 'рдордзреНрдпрдордГ'
"рдХреНрд░рд┐рдпрд╛рд╢реАрд▓рддрд╛ (1-5)" = 2
"Platform" = 'Telegram'
"рд╕рдЩреНрдХреЗрддрдГ" = 'https://rebrand.ly/sam-jalpa'
"рдЙрджрд╛рд╣рд░рдгрд╕рдиреНрджреЗрд╢рд╛рдГ" = ''
"рд╡рд┐рд╡рд░рдгрд╛рдирд┐" = ''

[[data]]
"рдирд╛рдо" = 'рд╕рдореНрднрд╛рд╖рдгрд╕рдВрд╕реНрдХреГрддрдЪрд┐рдиреНрддрд╛рдордгрд┐рдГ-рей'
"рд╡рд┐рд╖рдпрдГ" = 'рдЕрдирд┐рд╢реНрдЪрд┐рддрдГ'
"рдирд┐рдпрдорд╛рдГ" = ''
"рд╕реНрддрд░рдГ (1-5)" = 'рдордзреНрдпрдордГ'
"рдХреНрд░рд┐рдпрд╛рд╢реАрд▓рддрд╛ (1-5)" = ''
"Platform" = 'Whatsapp'
"рд╕рдЩреНрдХреЗрддрдГ" = 'https://chat.whatsapp.com/0OAomzAt6HP0qIEHr3cG2L'
"рдЙрджрд╛рд╣рд░рдгрд╕рдиреНрджреЗрд╢рд╛рдГ" = ''
"рд╡рд┐рд╡рд░рдгрд╛рдирд┐" = ''

[[data]]
"рдирд╛рдо" = 'рд╢рд╛рд░рджрд╛рдкреНрд░рдХрд╛рд╢рдГ'
"рд╡рд┐рд╖рдпрдГ" = 'рдЕрдирд┐рд╢реНрдЪрд┐рддрдГ'
"рдирд┐рдпрдорд╛рдГ" = '''
рд╕рдВрд╕реНрдХреГрддрд╕реНрдпреИрд╡ рдкреНрд░рдпреЛрдЧрдГред (рдЕрдиреБрдкреНрд░реЗрд╖рдгреЗрд╖реНрд╡рдкрд┐)
рд╕рд╛рдорд╛рдиреНрдпрд╕рдВрд╕реНрдХреГрддрдЧрдгреЛрд╜рдпрдВ, рдпрддреНрд░ рдХреЗрд╡рд▓рдВ рд╕рдВрд╕реНрдХреГрддрдореЗрд╡, рдирд╛рдиреНрдпрд╛ рднрд╛рд╖рд╛, рдкреНрд░рдпреБрдЬреНрдпрддреЗредЁЯСМ
рдкреНрд░рд╛рд░рдореНрднрд┐рдХрд╡реНрдпрд╛рдХрд░рдг-рднрд╛рд╖рд╛рдиреНрддрд░рдг-рд╕рд╛рд╣рд┐рддреНрдпрд╛рджрд┐рдХреНрд╖реЗрддреНрд░реЗрд╖реБ рдХрд╛рд░реНрдпрдВ рдХреБрд░реНрдо рдЗрддрд┐ рдзрд┐рдпрд╛ рдкреНрд░рд╛рд░рдмреНрдзреЛрд╜рдпрдВ рд╕рдВрдШрдГред ЁЯСП
рдЬрд┐рдЬреНрдЮрд╛рд╕реВрдирд╛рдВ рдкреНрд░рд╢реНрдирд╛рдирд╛рдВ, рд╕рдиреНрджреЗрд╣рд╛рдирд╛рдЮреНрдЪ рд╕рдорд╛рдзрд╛рдирдВ, рд╕реНрд╡рд▓рд┐рдЦрд┐рддрдХреГрддреАрдирд╛рдВ рд╡рд┐рдорд░реНрд╢рдирд╛рджрд┐рдХрдВ рдЪ рд╕рдкреНрд░реЗрдо рдкреНрд░рд╛рдкреНрдпрддреЗред'''
"рд╕реНрддрд░рдГ (1-5)" = 'рдордзреНрдпрдордГ'
"рдХреНрд░рд┐рдпрд╛рд╢реАрд▓рддрд╛ (1-5)" = 3
"Platform" = 'Whatsapp'
"рд╕рдЩреНрдХреЗрддрдГ" = 'https://chat.whatsapp.com/3BPRh8eLd642M303n6gnpk'
"рдЙрджрд╛рд╣рд░рдгрд╕рдиреНрджреЗрд╢рд╛рдГ" = ''
"рд╡рд┐рд╡рд░рдгрд╛рдирд┐" = ''


[[data]]
"рдирд╛рдо" = 'рд╕рдВрд╕реНрдХреГрдд-рдкрд╛рдХреНрд╖рд┐рдХ-рдкрддреНрд░рд┐рдХрд╛ рджреЗрд╣рд▓реНрдпрд╛рдГ'
"рд╡рд┐рд╖рдпрдГ" = 'рд╡рд╛рд░реНрддрд╛рдкрддреНрддреНрд░-рд╡рд┐рдХреНрд░рдпрдгрдореН?'
"рдирд┐рдпрдорд╛рдГ" = '?'
"рд╕реНрддрд░рдГ (1-5)" = '?'
"рдХреНрд░рд┐рдпрд╛рд╢реАрд▓рддрд╛ (1-5)" = ''
"Platform" = 'Whatsapp'
"рд╕рдЩреНрдХреЗрддрдГ" = 'https://chat.whatsapp.com/1ak9KArEjXN6NMleCA7UMm'
"рдЙрджрд╛рд╣рд░рдгрд╕рдиреНрджреЗрд╢рд╛рдГ" = ''
"рд╡рд┐рд╡рд░рдгрд╛рдирд┐" = ''

[[data]]
"рдирд╛рдо" = 'рд╕рдВрд╕реНрдХреГрддрдирд┐рдирд╛рджрдГ'
"рд╡рд┐рд╖рдпрдГ" = ''
"рдирд┐рдпрдорд╛рдГ" = ''
"рд╕реНрддрд░рдГ (1-5)" = ''
"рдХреНрд░рд┐рдпрд╛рд╢реАрд▓рддрд╛ (1-5)" = ''
"Platform" = 'Whatsapp'
"рд╕рдЩреНрдХреЗрддрдГ" = 'https://chat.whatsapp.com/HOtXh9MXVyeLLs7MKX3jUX'
"рдЙрджрд╛рд╣рд░рдгрд╕рдиреНрджреЗрд╢рд╛рдГ" = ''
"рд╡рд┐рд╡рд░рдгрд╛рдирд┐" = ''

[[data]]
"рдирд╛рдо" = 'рд╕рдВрд╕реНрдХреГрддрднрд╛рд░рддреА-рд╕реНрддреЛрддреНрд░рдЧрдгрдГ реи'
"рд╡рд┐рд╖рдпрдГ" = 'рд╕реНрддреЛрддреНрд░рд╛рдгрд┐'
"рдирд┐рдпрдорд╛рдГ" = ''
"рд╕реНрддрд░рдГ (1-5)" = ''
"рдХреНрд░рд┐рдпрд╛рд╢реАрд▓рддрд╛ (1-5)" = ''
"Platform" = 'Whatsapp'
"рд╕рдЩреНрдХреЗрддрдГ" = 'https://chat.whatsapp.com/GMrF97BSylCCpsqi7DyQbt'
"рдЙрджрд╛рд╣рд░рдгрд╕рдиреНрджреЗрд╢рд╛рдГ" = ''
"рд╡рд┐рд╡рд░рдгрд╛рдирд┐" = ''

[[data]]
"рдирд╛рдо" = ''
"рд╡рд┐рд╖рдпрдГ" = 'рд╕рдВрд╕реНрдХреГрддрдореН'
"рдирд┐рдпрдорд╛рдГ" = ''
"рд╕реНрддрд░рдГ (1-5)" = ''
"рдХреНрд░рд┐рдпрд╛рд╢реАрд▓рддрд╛ (1-5)" = ''
"Platform" = 'Discord'
"рд╕рдЩреНрдХреЗрддрдГ" = 'https://discord.gg/bFWFxZ'
"рдЙрджрд╛рд╣рд░рдгрд╕рдиреНрджреЗрд╢рд╛рдГ" = ''
"рд╡рд┐рд╡рд░рдгрд╛рдирд┐" = ''

[[data]]
"рдирд╛рдо" = 'рдЕрдирд╡рд░рддрдВ рд▓рд┐рдЦрдиреНрддреБ рд╕рдВрд╕реНрдХреГрддрдореН'
"рд╡рд┐рд╖рдпрдГ" = 'рд╕рдВрд╕реНрдХреГрддрдореН'
"рдирд┐рдпрдорд╛рдГ" = ''
"рд╕реНрддрд░рдГ (1-5)" = 1
"рдХреНрд░рд┐рдпрд╛рд╢реАрд▓рддрд╛ (1-5)" = ''
"Platform" = 'Whatsapp'
"рд╕рдЩреНрдХреЗрддрдГ" = 'https://chat.whatsapp.com/HsCzwQT3BAsKpLHosdpjwx'
"рдЙрджрд╛рд╣рд░рдгрд╕рдиреНрджреЗрд╢рд╛рдГ" = ''
"рд╡рд┐рд╡рд░рдгрд╛рдирд┐" = ''

[[data]]
"рдирд╛рдо" = 'samskrita'
"рд╡рд┐рд╖рдпрдГ" = 'рдЕрдирд┐рд╢реНрдЪрд┐рддрдГ'
"рдирд┐рдпрдорд╛рдГ" = 'рд╕рдВрд╕реНрдХреГрддрд╕реНрдпреИрд╡ рдкреНрд░рдпреЛрдЧрдГред (рдЕрдиреБрдкреНрд░реЗрд╖рдгреЗрд╖реНрд╡рдкрд┐)'
"рд╕реНрддрд░рдГ (1-5)" = 'рд╕рд╛рд░реНрд╡рддреНрд░рд┐рдХрдГ'
"рдХреНрд░рд┐рдпрд╛рд╢реАрд▓рддрд╛ (1-5)" = 1
"Platform" = 'slack'
"рд╕рдЩреНрдХреЗрддрдГ" = ''
"рдЙрджрд╛рд╣рд░рдгрд╕рдиреНрджреЗрд╢рд╛рдГ" = ''
"рд╡рд┐рд╡рд░рдгрд╛рдирд┐" = ''

[[data]]
"рд╡рд┐рд╖рдпрдГ" = 'рд╕рдВрд╕реНрдХреГрддрдореН'
"рдирд╛рдо" = 'Sanskrit club'
"рд╕рдЩреНрдХреЗрддрдГ" = 'https://www.joinclubhouse.com/club/sanskrit'
"рднрд╛рд╖рд╛\n" = 'рд╕рдВрд╕реНрдХреГрддрдореН'
"рдирд┐рдпрдорд╛рдГ" = 'https://www.sanskrit.club/'
"рд╕рдХреНрд░рд┐рдпрддрд╛" = ''
"Platform" = 'Clubhouse'
